### ISSUE TITLE
Distribution parameters and branch length

### ISSUE THREAD

**Issue by reymonera** [gtonkinhill/panstripe#6]
Hi,

I'm trying to do some descriptions about the pangenome of a conserved bacteria. Said bacteria hasn't shown much diversity in previous analysis and I would like to describe its pangenome better, hence why I'm exploring Panstripe. Thanks for the tool, since the conclusions are fairly interesting.

I any case, certain doubts have arisen for me: I understand that Panstripe uses a Poisson distribution for the gene gain/loss events. However, when dealing with such taxonomic groups with short branches, it was advised to change the "family" parameter to Gaussian. I wanted to know the following:

- Does this means that my analysis now assumes a Gaussian distribution for the gain/loss events instead of the Poisson distribution?
- When obtaining the estimate vs. parameter box-plot: The estimates values on the y-axis seem to be very different comparing them to the examples provided in this repository. Is this because of the Gaussian distribution?
- In the same plot: The core parameter has the widest estimate while the tip parameter is near 0. I was wondering if this is because of the short-length branches in my phylogeny.
- In the cumulative gene gain&loss events vs. cumulative core branch distance: I now that my phylogeny has a non-confirmed sub-species. This non-confirmed sub-species appears as having a relatively long branch compared with the others in my phylogeny. When I see the dots in this plot, there is a terminal branch that definitely appears on the far-end of the plot, completely outside the other branch lengths. I guess this would be said sub-species branch. I was wondering if this meant that this non-confirmed sub-species may be causing some noise in the description of this pangenome.

Thanks for any answer you could give me. I'm still working on understanding my data better with this tool.

Regards,

Camila

**Comment by gtonkinhill** [comment]
Hi,

1. The default model is a `Tweedie` distribution but yes if you change the family to `Gaussian` it will assume that the total number of gain & loss on a branch is Gaussian. 
2. The examples in the repository are not representative of all datasets. The parameters will depend a lot on the branch lengths in your phylogeny and the scale used. i.e if you used dates you would get very different values to branches scaled by the number of mutations.
3. Again, this is probably due to the different scale used in your branch lengths rather than because of a subset of shorter branches. In general, you would normally be interested in comparing the same parameter between datasets rather than the parameters within a dataset.
4. This is likely just a reflection of some outlier branch lengths. If you are worried about the impact it is having you could try removing it from the phelogeny and investigating the impact on the inferred parameters. You could also look at some alternative plots using the `plot_pangenome_curve` or `plot_pairwise` functions.

I hope this helps!
